[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "DFmH3PDLA646d2iPcing9FdKEzMzjzDeT11VCBrVEZKZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ahzam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
